### ISSUE TITLE
Compatibility with Python 3

### ISSUE THREAD

**Issue by scheunemann** [ggueret/pelican-dashify#2]
Hey, thanks for your plugin and work!

I figured when I want to use it with Python 3 it is not working (despite claiming it in the `setup.py`).

The following issues occur on `make html`:

- `CRITICAL: NameError: name 'unicode' is not defined`
- `CRITICAL: AttributeError: 'dict' object has no attribute 'iteritems'`

**Comment by ggueret** [comment]
Hey, thanks @scheunemann for this very first contribution on Pelican-dashify !
Indeed the Python 3 compatibility is not assured despite what the setup file says, sorry about that.

This is the opportunity for me to add some tests to validate the supported versions (related to #1).
It will be done this week-end, it's motivating to know that pelican-dashify is used :)

Then we will be able to test this pull request then merge-it into master to make a new release !

**Comment by scheunemann** [comment]
@ggueret I've seen you started setting up continous integration, nice! ... and certainly the way to go. Having said that, I tested the stuff above on latest Arch Linux but I am fine to see what travis says about that.

My pleasure providing some indoor fun for the rainy/cloudy weekend ahead :) Again, thank you for the plugin.

**Comment by ggueret** [comment]
That was done this last week in https://github.com/ggueret/pelican-dashify/commit/3d79cc0f575183faefbe8db80e20ec4ca0dedf64. With a bit of latency there, sorry!
Also added travis-ci integration with a functional test. Your contributions are very welcome and I will look into these following issues this next days.

Thanks for the Python 3 compatibility @scheunemann !
