### ISSUE TITLE
Videos are not discovered on pages

### ISSUE THREAD

**Issue by scheunemann** [ggueret/pelican-dashify#4]
If I want to include a video on a page with doing all steps like in the README but replacing `article` with `page` in the template example, I get the following error:

```bash
CRITICAL: UndefinedError: 'str object' has no attribute 'duration'
```
Or, with adaptation of the template, it simply just won't play the video.

**Comment by scheunemann** [comment]
@ggueret please see my PR. I have tested it, works fine if one updates the template accordingly.

**Comment by ggueret** [comment]
Ah, yes, I did not see right away !

Thanks again ;)

**Comment by scheunemann** [comment]
> Ah, yes, I did not see right away !
> 
> Thanks again ;)

You're very welcome! :)
